// ─── Feature Manifest ─────────────────────────────────────────────────────────

/**
 * Describes a page route stub that the CLI generates when `add <feature>` is run.
 */
export interface RouteStub {
  /** Next.js route segment, e.g. "[locale]/events" */
  segment: string;
  exports: {
    /** Default export name from the feature package */
    default: string;
    /** generateMetadata export name, if applicable */
    generateMetadata?: string;
  };
  /** If true, the CLI wraps the stub in admin-only protection comments */
  adminOnly?: boolean;
}

/**
 * Describes an API route stub that the CLI generates.
 */
export interface ApiRouteStub {
  /** Next.js route segment, e.g. "api/events/[id]" */
  segment: string;
  methods: Array<"GET" | "POST" | "PATCH" | "PUT" | "DELETE">;
}

/**
 * The contract between a feature package and @mohasinac/cli.
 * Every feat-* package exports a `manifest` object satisfying this interface.
 */
export interface FeatureManifest {
  /** Unique feature identifier, matches FeaturesConfig key */
  name: string;
  /** next-intl namespace key for this feature's messages */
  i18nNamespace: string;
  /** Environment variable keys required by this feature (documentation only) */
  envKeys: string[];
  /** Page route stubs generated by CLI on install */
  routes: RouteStub[];
  /** API route stubs generated by CLI on install */
  apiRoutes: ApiRouteStub[];
}

// ─── Features Config ──────────────────────────────────────────────────────────

/**
 * Shape of features.config.ts in consumer projects.
 * Keys are feature names; values are booleans (enabled/disabled).
 *
 * @example
 * ```ts
 * export default {
 *   auth: true,
 *   events: true,
 *   auctions: false,
 * } satisfies FeaturesConfig;
 * ```
 */
export type FeaturesConfig = Record<string, boolean>;
