/**
 * Shared file system and manifest utilities used by CLI commands.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import type {
  FeatureManifest,
  RouteStub,
  ApiRouteStub,
} from "@mohasinac/contracts";

// ─── Project root detection ────────────────────────────────────────────────

/**
 * Walks up from cwd to find the project root (contains package.json with "next" dep).
 */
export function findProjectRoot(cwd: string = process.cwd()): string {
  let dir = cwd;
  while (true) {
    const pkgPath = join(dir, "package.json");
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as Record<
          string,
          unknown
        >;
        const deps = {
          ...((pkg.dependencies ?? {}) as Record<string, unknown>),
          ...((pkg.devDependencies ?? {}) as Record<string, unknown>),
        };
        if ("next" in deps) return dir;
      } catch {
        // continue walking up
      }
    }
    const parent = dirname(dir);
    if (parent === dir)
      throw new Error("Could not find Next.js project root from: " + cwd);
    dir = parent;
  }
}

// ─── Manifest loading ──────────────────────────────────────────────────────

/**
 * Resolves a feature manifest from a local packages/ directory (monorepo)
 * or from node_modules (installed package).
 *
 * Looks for: packages/feat-{name}/manifest.ts  (source)
 *         or node_modules/@mohasinac/feat-{name}/dist/esm/manifest.js  (built)
 */
export async function loadManifest(
  name: string,
  projectRoot: string,
): Promise<FeatureManifest> {
  // 1. Try monorepo source (packages/feat-<name>/src/manifest.ts transpiled at runtime)
  const monoSrcPath = join(
    projectRoot,
    "packages",
    `feat-${name}`,
    "src",
    "manifest.ts",
  );
  const monoJsPath = join(
    projectRoot,
    "packages",
    `feat-${name}`,
    "dist",
    "esm",
    "manifest.js",
  );
  // 2. Try installed package
  const pkgPath = join(
    projectRoot,
    "node_modules",
    "@mohasinac",
    `feat-${name}`,
    "dist",
    "esm",
    "manifest.js",
  );

  const tryPaths = [monoJsPath, pkgPath];
  let mod: { manifest: FeatureManifest } | null = null;

  for (const p of tryPaths) {
    if (existsSync(p)) {
      mod = (await import(/* @vite-ignore */ `file://${p}`)) as {
        manifest: FeatureManifest;
      };
      break;
    }
  }

  if (!mod) {
    // Fall back to the local source manifest.ts via dynamic import if running in ts-node/tsx
    if (existsSync(monoSrcPath)) {
      mod = (await import(/* @vite-ignore */ `file://${monoSrcPath}`)) as {
        manifest: FeatureManifest;
      };
    }
  }

  if (!mod?.manifest) {
    throw new Error(
      `Cannot find manifest for @mohasinac/feat-${name}. ` +
        `Tried:\n  ${tryPaths.join("\n  ")}`,
    );
  }

  return mod.manifest;
}

// ─── Stub generation ───────────────────────────────────────────────────────

/**
 * Generates a 2-line route stub for a page.
 *
 * @example
 * // app/[locale]/events/page.tsx
 * export { EventsPage as default, generateMetadata } from "@mohasinac/feat-events";
 */
export function generateRouteStub(
  stub: RouteStub,
  featureName: string,
): string {
  const { default: def, generateMetadata: gm } = stub.exports;
  const named = gm ? `{ ${def} as default, ${gm} }` : `{ ${def} as default }`;
  return `// Auto-generated by @mohasinac/cli — do not edit\nexport ${named} from "@mohasinac/feat-${featureName}";\n`;
}

/**
 * Generates a 2-line API route stub.
 *
 * @example
 * // app/api/events/route.ts
 * export { GET, POST } from "@mohasinac/feat-events/api/events";
 */
export function generateApiRouteStub(
  stub: ApiRouteStub,
  featureName: string,
): string {
  const methods = stub.methods.join(", ");
  const segment = stub.segment; // e.g. "api/events/[id]"
  return `// Auto-generated by @mohasinac/cli — do not edit\nexport { ${methods} } from "@mohasinac/feat-${featureName}/${segment}";\n`;
}

// ─── File writing helpers ──────────────────────────────────────────────────

/** Writes a stub file, creating directories as needed. Skips if file already exists. */
export function writeStub(
  filePath: string,
  content: string,
): "created" | "skipped" {
  if (existsSync(filePath)) return "skipped";
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, content, "utf-8");
  return "created";
}

// ─── features.config.ts patching ──────────────────────────────────────────

/**
 * Reads features.config.ts or features.config.js from the project root,
 * sets the given feature key to the given value, and writes it back.
 *
 * Works via string manipulation — no AST parsing required for simple cases.
 */
export function patchFeaturesConfig(
  projectRoot: string,
  featureKey: string,
  value: boolean,
): void {
  const candidates = [
    join(projectRoot, "features.config.ts"),
    join(projectRoot, "features.config.js"),
  ];
  const configPath = candidates.find(existsSync);
  if (!configPath) {
    console.warn("  ⚠  features.config.ts not found — skipping config patch");
    return;
  }

  let source = readFileSync(configPath, "utf-8");
  const valueStr = String(value);

  // Try to replace an existing key: e.g.  events: false  →  events: true
  const existingPattern = new RegExp(
    `(\\b${featureKey}\\s*:\\s*)(true|false)`,
    "g",
  );
  if (existingPattern.test(source)) {
    source = source.replace(existingPattern, `$1${valueStr}`);
  } else {
    // Key not found — insert before the closing } satisfies FeaturesConfig
    source = source.replace(
      /(}\s*satisfies\s*FeaturesConfig)/,
      `  ${featureKey}: ${valueStr},\n$1`,
    );
  }

  writeFileSync(configPath, source, "utf-8");
}

// ─── .env.example patching ────────────────────────────────────────────────

/** Appends missing env keys to .env.example. */
export function patchEnvExample(projectRoot: string, envKeys: string[]): void {
  if (envKeys.length === 0) return;
  const envPath = join(projectRoot, ".env.example");
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf-8") : "";
  const missing = envKeys.filter((k) => !existing.includes(k));
  if (missing.length === 0) return;
  const block =
    "\n# Added by @mohasinac/cli\n" +
    missing.map((k) => `${k}=`).join("\n") +
    "\n";
  writeFileSync(envPath, existing + block, "utf-8");
}
