/**
 * File generators — produces the content of every scaffolded config file.
 */

import type { ProviderSelections } from "./providers.js";
import { collectEnvKeys } from "./providers.js";

// ─── next.config.js ───────────────────────────────────────────────────────────

export function generateNextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const { withFeatures } = require("@mohasinac/cli/next");
const features = require("./features.config").default;

module.exports = withFeatures(features)({
  serverExternalPackages: ["firebase-admin"],
  images: {
    remotePatterns: [
      { hostname: "firebasestorage.googleapis.com" },
      { hostname: "storage.googleapis.com" },
    ],
  },
});
`;
}

// ─── i18n/request.ts ──────────────────────────────────────────────────────────

export function generateI18nRequest(locales: string[]): string {
  const defaultLocale = locales[0] ?? "en";
  return `import { getRequestConfig } from "next-intl/server";
import { mergeFeatureMessages } from "@mohasinac/cli/i18n";
import features from "../../features.config";

export default getRequestConfig(async ({ locale }) => {
  const base = (await import(\`../../messages/\${locale}.json\`)).default;
  const feature = await mergeFeatureMessages(locale, features);
  return {
    locale,
    messages: { ...feature, ...base },
  };
});
`;
}

// ─── middleware.ts ────────────────────────────────────────────────────────────

export function generateMiddleware(locales: string[], auth: ProviderSelections["auth"]): string {
  const localeList = JSON.stringify(locales);
  const defaultLocale = locales[0] ?? "en";

  if (auth === "firebase") {
    return `import { createMiddlewareAuthChain } from "@mohasinac/auth-firebase";
import createIntlMiddleware from "next-intl/middleware";
import { NextRequest } from "next/server";

const intlMiddleware = createIntlMiddleware({
  locales: ${localeList},
  defaultLocale: "${defaultLocale}",
});

const authMiddleware = createMiddlewareAuthChain({
  protectedPaths: ["/account", "/checkout", "/orders", "/seller", "/admin"],
  adminPaths: ["/admin"],
});

export async function middleware(request: NextRequest) {
  const intlResult = intlMiddleware(request);
  if (!intlResult.headers.get("x-middleware-next")) return intlResult;
  return authMiddleware(request);
}

export const config = {
  matcher: ["/((?!api|_next|.*\\\\..*).*)"],
};
`;
  }

  // nextauth / clerk — simpler
  return `import createIntlMiddleware from "next-intl/middleware";
import { NextRequest } from "next/server";

const intlMiddleware = createIntlMiddleware({
  locales: ${localeList},
  defaultLocale: "${defaultLocale}",
});

export function middleware(request: NextRequest) {
  return intlMiddleware(request);
}

export const config = {
  matcher: ["/((?!api|_next|.*\\\\..*).*)"],
};
`;
}

// ─── constants/site.ts ────────────────────────────────────────────────────────

export function generateSiteConfig(projectName: string, locales: string[]): string {
  const defaultLocale = locales[0] ?? "en";
  return `import type { SiteConfig } from "@mohasinac/contracts";

const SITE_CONFIG: SiteConfig = {
  name: "${projectName}",
  tagline: "",
  description: "",
  url: "https://example.com",
  logoUrl: "/images/logo.svg",
  logoAlt: "${projectName} logo",
  email: {
    fromAddress: "noreply@example.com",
    supportAddress: "support@example.com",
  },
  currency: "USD",
  defaultLocale: "${defaultLocale}",
  locales: ${JSON.stringify(locales)},
};

export default SITE_CONFIG;
`;
}

// ─── constants/theme.ts ───────────────────────────────────────────────────────

export function generateThemeConfig(): string {
  return `/**
 * Theme constants — map to CSS custom properties defined in tokens.css.
 * Import these instead of hard-coding Tailwind class names.
 */
export const THEME = {
  colors: {
    primary:   "var(--lir-color-primary)",
    secondary: "var(--lir-color-secondary)",
    accent:    "var(--lir-color-accent)",
    surface:   "var(--lir-color-surface)",
    muted:     "var(--lir-color-muted)",
  },
  radius: {
    sm:   "var(--lir-radius-sm)",
    md:   "var(--lir-radius-md)",
    card: "var(--lir-radius-card)",
  },
  font: {
    sans: "var(--lir-font-sans)",
  },
} as const;
`;
}

// ─── .env.example ─────────────────────────────────────────────────────────────

export function generateEnvExample(selections: ProviderSelections): string {
  const keys = collectEnvKeys(selections);
  const lines = keys.map((k) => `${k}=`);
  return `# Generated by @mohasinac/create-app
# Fill in the values for your chosen providers.

${lines.join("\n")}

# Optional — uncomment as needed
# NEXT_PUBLIC_BASE_URL=http://localhost:3000
# RATE_LIMIT_UPSTASH_URL=
# RATE_LIMIT_UPSTASH_TOKEN=
`;
}

// ─── app/layout.tsx ───────────────────────────────────────────────────────────

export function generateRootLayout(projectName: string, locales: string[]): string {
  const defaultLocale = locales[0] ?? "en";
  return `import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "@/providers.config";

export const metadata: Metadata = {
  title: "${projectName}",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={params.locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
`;
}
